version: '3'

services:
  app:
    build: .
    container_name: "app"
    volumes:
      - ./app/hello-1.0.war:/tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war


  web:
    image: "tomcat:alpine"
    ports:
      - "8080:8080"
    volumes:
      - ./app/hello-1.0.war:/usr/local/tomcat/webapps/hello-1.0.war